#!/bin/sh

set -eu
set -o pipefail

allowed_clients=$NFS_SERVER_ALLOWED_CLIENTS
export_options=$NFS_SERVER_EXPORT_OPTIONS

data_dir=/mnt/data
if [ ! -d "$data_dir" ]; then
    echo "no data directory found at $data_dir" >&2
    exit 1
fi

rm -f /etc/exports
echo "/mnt/data $allowed_clients($export_options)" >/etc/exports
exportfs -rv

nfsd_debug_opt=
mountd_debug_opt=
if [ $NFS_SERVER_DEBUG -eq 1 ]; then
    nfsd_debug_opt=$NFS_SERVER_NFSD_DEBUG_OPT
    mountd_debug_opt=$NFS_SERVER_MOUNTD_DEBUG_OPT
fi

mount -t nfsd nfsd /proc/fs/nfsd

rpc.nfsd -N 3 -V 4 --grace-time 10 $nfsd_debug_opt &
rpc.mountd -N 2 -N 3 -V 4 --foreground $mountd_debug_opt &

wait